backend:
  name: git-gateway
  branch: main
# local_backend: true # Set to true when developing locally

media_folder: public/assets
public_folder: assets
collections:
  - name: "posts"
    label: "Blog Posts"
    description: >
      Create blog posts here
    folder: "content/posts"
    slug: "{{fields.date}}_{{fields.slug}}"
    summary: "{{day}}-{{month}}-{{year}} {{fields.title}}"
    create: true
    fields:
      - { label: "Template", name: "template", widget: "hidden", default: "blog-post" }
      - {
          label: "Title",
          name: "title",
          widget: "string",
          tagname: "h1",
          hint: "Title for the blog post",
        }
      - {
          label: "Slug",
          name: "slug",
          widget: "string",
          hint: "Start slug with /. Use only alphanumeric characters, - and _. Avoid spaces in any cases.",
        }
      - {
          label: "Summary",
          name: "summary",
          widget: "string",
          hint: "Summary for the blog post displayed in the list view.",
        }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          dateFormat: "YYYY-MM-DD",
          timeFormat: "HH:mm",
          format: "YYYY-MM-DD HH:mm",
        }
      - {
          label: "SEO Description",
          name: "seoDescription",
          widget: "text",
          hint: "Short description for the meta description tag.",
        }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Blog Image", name: "blogImage", widget: "image", hint: "Blog Post image" }
      - { label: "Body", name: "body", widget: "markdown", hint: "Main blog content" }

  - name: "pages"
    label: "Pages"
    files:
      - label: "Projects"
        name: "projects"
        file: "content/pages/projects.json"
        fields:
          - label: "Projects"
            name: "projects"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string", hint: "Name of the project" }
              - {
                  label: "Description",
                  name: "description",
                  widget: "text",
                  hint: "Description of the project",
                }
              - {
                  label: "Tags",
                  name: "tags",
                  widget: "list",
                  hint: "Technologies used in the project",
                }
              - {
                  label: "Github Link",
                  name: "githubLink",
                  widget: "string",
                  hint: "Github link of the project",
                }
              - {
                  label: "Live Link",
                  name: "liveLink",
                  widget: "string",
                  hint: "Link where the project is live",
                  required: false,
                }
              - {
                  label: "Project Image",
                  name: "projectImage",
                  widget: "image",
                  hint: "Image of the project",
                }

  - name: settings
    label: Settings
    files:
      - name: general
        label: General
        file: "src/config/site.json"
        fields:
          - widget: string
            name: siteUrl
            label: Website URL
          - widget: string
            name: defaultTitle
            label: Site Title
          - widget: text
            name: defaultDescription
            label: Site Description
          - widget: image
            name: defaultImage
            label: Site Image
          - widget: image
            name: iconImage
            label: favicon

      - name: personal-info
        label: "Personal Info"
        file: "src/config/personal_info.json"
        fields:
          - widget: string
            name: name
            label: Your name
          - widget: text
            name: shortDescription
            label: Short description about yourself
          - widget: text
            name: aboutMe
            label: About Me
          - widget: list
            name: occupations
            label: My Occupations
          - widget: list
            name: skills
            label: Your skills
          - widget: string
            name: emailId
            label: Email ID
          - widget: string
            name: githubId
            label: Github ID
          - widget: string
            name: twitterId
            label: Twitter ID
          - widget: string
            name: linkedinId
            label: Linkedin ID
          - label: Personal Logo Image
            name: logoImage
            widget: image
